# ===============================
# DATABASE SQLITE
# ===============================

spring.datasource.url=jdbc:sqlite:smartatm.db

spring.datasource.driver-class-name=org.sqlite.JDBC


# ===============================
# JPA / HIBERNATE
# ===============================

spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect

spring.jpa.hibernate.ddl-auto=create

spring.jpa.show-sql=true


# ===============================
# SERVER
# ===============================

server.port=8080